### PR TITLE
:ok_hand: fabien

### PR DESCRIPTION
**Pull request by fabienjuif**

### CODE REVIEW

**Comment by guillaumecrespel** [comment]
What do you think about remove `memo` on `Label` and `Path` ?
memo on `DefaultLink` is enough I think ?

**Comment by fabienjuif** [comment]
In my mind you have tested it (perf before/after on a big dataset) and this is why you kept them.

If this is not the case, we should remove them for now.

**Comment by guillaumecrespel** [comment]
ok, I think not :/
I merge your PR, and remove this optimisation in mine ?

**Comment by fabienjuif** [comment]
yes

**Pull request merged**
